dist: trusty
sudo: false
language: python
python:
- '3.6'
git:
  depth: false
branches:
  only:
  - master
  - develop
  - /^[0-9]+/
stages:
  - name: testing
  - name: deploying
jobs:
  include:
    - stage: testing
      name: flake8
      sudo: false
      install: pip install -c constraints.txt -r requirements.txt
      script:
        - flake8
    - stage: testing
      name: black
      sudo: false
      install: pip install -c constraints.txt black
      script:
        - black --check setup.py tlwatch
    - stage: testing
      name: mypy
      sudo: false
      install: pip install -c constraints.txt -r requirements.txt
      script:
        - mypy --ignore-missing-imports tlwatch
    - stage: deploying
      name: docker
      env:
        - DOCKER_USER=trustlinesautomation
        # DOCKER_PASSWORD:
        - secure: "UDzsL7Yd8D2kDIMFgtFxR+aNwIavgZYqrnwmU2AAgLc/md4Uxp+5agtN/+mjT61KHHBW1mFzgHMQIqMalg3D8Nhw6QLWzwVx8hd2YsdHFe5BhW1scFGjwmCOiFHGLFLDD6sAVsQI9PY9wZP797FJWs/Roj8wjnEM7zC7UVSDCMt+lfDtfe5V7rHF7kfqaOzTMETYk6au2cxc6X03DJGAp4oZLTOXnDCUSHxyl2RcziWxFbFqNx+kd6zWcUV4lj51OMgQMsMlUJNo+odmF8ShxAU+aojTGEHC6pXJEj+qyjX65CJzk1p4OBjYG2tSVCZsTnDTaJJxMZ6CtkwjtBudQvLtHl/gSiY7ho3O6WUecm8uW9WnXnL7jP24IYN9P1/yaqQK73+7cm2rSDuxPTevASN8q1Xldiq32/8Vsojou5gCpLv828bL0Y0gYpTudNKn2xw0mqAwN6i7SVPiJRDnD9oKtd9DpiTpO+lL+ktmGx9lE+RGxMbkR9DzRSXZtcEIwY0IeIPQUxJ1dbhiSnKaGtmvBKnox/5BRCF87B0/nZZDPvWfJdHOmib5rI9FvVRTh5dGFPpQU9k7FQjgy9jgcWQlKsDAobiODM0uPn8ckgwLyQmJbfHqt0gMOB+vRgPiFCgR/9oIG3WP0K4QQWZ8jbiwYL0+B4y7v3k7FoUR7JM="

      install: /bin/true
      sudo: true
      service: docker
      script:
        - docker build -t watch .
      deploy:
        skip_cleanup: true
        provider: script
        script: ".travis/push-docker-image"
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(develop|[0-9]+.*)$
