dist: trusty
sudo: false
language: python
python:
- '3.6'
git:
  depth: false
branches:
  only:
  - master
  - develop
  - pypi
  - /^[0-9]+/
stages:
  - name: testing
  - name: deploying
jobs:
  include:
    - stage: testing
      name: flake8
      sudo: false
      install: pip install -c constraints.txt -r requirements.txt
      script:
        - flake8
    - stage: testing
      name: black
      sudo: false
      install: pip install -c constraints.txt black
      script:
        - black --check setup.py tlwatch
    - stage: testing
      name: mypy
      sudo: false
      install: pip install -c constraints.txt -r requirements.txt
      script:
        - mypy --ignore-missing-imports tlwatch
    - stage: deploying
      name: docker
      env:
        - DOCKER_USER=trustlinesautomation
        # DOCKER_PASSWORD:
        - secure: "UDzsL7Yd8D2kDIMFgtFxR+aNwIavgZYqrnwmU2AAgLc/md4Uxp+5agtN/+mjT61KHHBW1mFzgHMQIqMalg3D8Nhw6QLWzwVx8hd2YsdHFe5BhW1scFGjwmCOiFHGLFLDD6sAVsQI9PY9wZP797FJWs/Roj8wjnEM7zC7UVSDCMt+lfDtfe5V7rHF7kfqaOzTMETYk6au2cxc6X03DJGAp4oZLTOXnDCUSHxyl2RcziWxFbFqNx+kd6zWcUV4lj51OMgQMsMlUJNo+odmF8ShxAU+aojTGEHC6pXJEj+qyjX65CJzk1p4OBjYG2tSVCZsTnDTaJJxMZ6CtkwjtBudQvLtHl/gSiY7ho3O6WUecm8uW9WnXnL7jP24IYN9P1/yaqQK73+7cm2rSDuxPTevASN8q1Xldiq32/8Vsojou5gCpLv828bL0Y0gYpTudNKn2xw0mqAwN6i7SVPiJRDnD9oKtd9DpiTpO+lL+ktmGx9lE+RGxMbkR9DzRSXZtcEIwY0IeIPQUxJ1dbhiSnKaGtmvBKnox/5BRCF87B0/nZZDPvWfJdHOmib5rI9FvVRTh5dGFPpQU9k7FQjgy9jgcWQlKsDAobiODM0uPn8ckgwLyQmJbfHqt0gMOB+vRgPiFCgR/9oIG3WP0K4QQWZ8jbiwYL0+B4y7v3k7FoUR7JM="

      install: /bin/true
      sudo: true
      service: docker
      script:
        - docker build -t watch .
      deploy:
        skip_cleanup: true
        provider: script
        script: ".travis/push-docker-image"
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(develop|[0-9]+.*)$
    - stage: deploying
      name: pypi
      install: /bin/true
      script:
        - /bin/true
      deploy:
        - provider: pypi
          skip_cleanup: true
          user: trustlines
          password:
            secure: "tL9LXHMNN3SnWAh1GRjBUMb+2oXQVndUyKvH28KD3vAVMD1hjhcNOs+qsmCSpLNFJBSwswXTbe1m/d6hlE2epcsx1mVZvtMvkjrEWkXLfaoZrqddoAF+b9+tpiIbG4XkB5tVF5WJhvzdSTQzvvtoMBouwj9rKalclFnWDHuacNqswClwDZBMH7l4RVj09b6HK9EA5mdDCvI0VzKxcekwa5wsdB4GLD8Y5oIipwkwFdk5/sdFRzzgZZsa3F+kpcDix60xms+5WoUNZfpNPhD/XDN57N73wOUSHcQoqad3QDFqiBARASFwqsNlkdvzmBnPA3A+1J6KhE439zVAXyl9Xww30n1QrLJbjLcGLl1m1WiJrgZyKIFdml9HbQqf1jlBcUKXCeSOqynx61eBHP8QnPZSZ6UOlb2N5btvwBrNtKVg/3+/RnTDoFBi/SPwubdH2JCHmFMhMgVEJUS7san+6PMha4HjcVtZNcKkK8lq+m2vff3+JIguxCPeQE2nfoewoEHULYK+xfe5pVj/sm3Zl64gfooSFmjHyFaEOVF/xLPx0+W26XVycvEaOCDJBPBwYGoXAI+mTl8rdH/dyKPgHzZlMjCQ+uVl6bI1FSb5SSBBm1D/UoT8FrsjTw9aVrg5Ppp3Pqib6tPyJxfbECUyEhyC/yuGoKL93SRhFjpBSR4="
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^([0-9]+.*)$
